### PR TITLE
ft #162781880 Serializer

### PR DESCRIPTION
**Pull request by Nicanor008**
### What does this PR do?
This PR implements readability of data in human readable format, that is JSON, from the database.

### Description of the PR
The PR converts data from database to JSON
It also validates the data obtained from the database
Data obtained by the serialiser will be displayed to the users in views

### How can this PR be manually tested?
Clone this repo at https://github.com/eduhmik/fd-djangoBlog-api.git
Checkout to branch `ft-serializer-162781880`
Create a virtual environment using `virtualenv env`
Activate the virtual environment using the command `source env/bin/activate` on linux and mac
`source env/scripts/activate` on windows
Run `pip install -r requirements.txt`
Run tests in terminal `python manage.py test`
Then run our project using python manage.py runserver
Open using your favourite browser

### Relevant PT stories
#162781880

### Any Background information
None

### CODE REVIEW

**Comment by Hesbon5600** [comment]
It's awesome according to me.

**Comment by Hesbon5600** [comment]
Change the root branch. You've raised a PR to master

**Comment by Nicanor008** [comment]
got it Hesbon. Doing so

**Comment by eduhmik** [comment]
Well done job. Thumbs up! What does the three dots at the end of class meta in user do?

**Comment by Nicanor008** [comment]
@eduhmik It indicates more outputs to be added

**Pull request merged**
